import { Platform } from 'react-native';

const Images = {
  nyc: require('../assets/images/sponsors/nyc.png'),
  coa: require('../assets/images/sponsors/coa.png'),
  mother: require('../assets/images/mother.jpg'),
  church: require('../assets/images/church.jpg'),
  oyer: require('../assets/images/oyer.png'),
  black: require('../assets/images/black.jpg'),
  francis: require('../assets/images/francis.jpg'),
  paige: require('../assets/images/paige.png'),
  pearl: require('../assets/images/pearls.jpg'),
  incarnate: require('../assets/images/incarnate.jpg'),
  CuratorsChoice: require('../assets/images/CuratorsChoice.png'),
  BlackandBrownLivesMatter: require('../assets/images/BlackandBrownLivesMatter.jpg'),
  DesignOfTheDecades: require('../assets/images/DesignOfTheDecades.jpeg'),
  HorrorComedyPicture: require('../assets/images/HorrorComedyPicture Show.jpg'),
  HereAndNow: require('../assets/images/HereAndNow.png'),
  MirrorTellsAStory: require('../assets/images/MirrorTellsAStory.jpg'),
  DoubleFeatureHorrorComedy: require('../assets/images/DoubleFeatureHorrorComedy.jpg'),
  NSFW: require('../assets/images/NSFW.jpg'),
  OMGLOLWTF: require('../assets/images/OMGLOLWTF.jpg'),
  OpeningNight: Platform.OS === 'ios' ? require('../assets/images/OpeningNight_IOS.jpg') : require('../assets/images/OpeningNight.jpg'),
  ReOrientations: require('../assets/images/ReOrientations.jpg'),
  SweetandSilverSalute: require('../assets/images/SweetandSilverSalute.jpg'),
  activeInfoIcon: require('../assets/images/Icons/icon-more-active.png'),
  activeLocationIcon: require('../assets/images/Icons/icon-venue-active.png'),
  activeInstallations: require('../assets/images/Icons/icon-location-active.png'),
  activeScheduleIcon: require('../assets/images/Icons/icon-schedule-active.png'),
  arrowIcon: require('../assets/images/Icons/icon-arrow.png'),
  backButton: require('../assets/images/Icons/back-button.png'),
  background: require('../assets/images/BG.png'),
  blowhorn: require('../assets/images/Icons/icon-blowhorn.png'),
  chevronIcon: require('../assets/images/Icons/icon-chevron.png'),
  closeButton: require('../assets/images/Icons/close-button.png'),
  coffeeParty: {uri: 'https://s-i.huffpost.com/gen/2263316/images/n-MIX-628x314.jpg'},
  directionsIcon: require('../assets/images/Icons/icon-directions.png'),
  faq: require('../assets/images/Icons/faq-icon.png'),
  gradArmory: require('../assets/images/dreamhouse.png'),
  inactiveInfoIcon: require('../assets/images/Icons/icon-more.png'),
  inactiveLocationIcon: require('../assets/images/Icons/icon-venue.png'),
  inactiveScheduleIcon: require('../assets/images/Icons/icon-schedule.png'),
  inactiveInstallations: require('../assets/images/Icons/icon-location.png'),
  lunchBreak: {uri: 'http://bedfordandbowery.com/wp-content/uploads/2015/11/22424764019_e150499ab9_z.jpg'},
  lyftButton: require('../assets/images/lyft-button.png'),
  markerIcon: require('../assets/images/Icons/icon-marker.png'),
  phase10: require('../assets/images/Icons/sun-phases/phase10.png'),
  phase11: require('../assets/images/Icons/sun-phases/phase11.png'),
  phase12: require('../assets/images/Icons/sun-phases/phase12.png'),
  phase13: require('../assets/images/Icons/sun-phases/phase13.png'),
  phase14: require('../assets/images/Icons/sun-phases/phase14.png'),
  phase15: require('../assets/images/Icons/sun-phases/phase15.png'),
  phase16: require('../assets/images/Icons/sun-phases/phase16.png'),
  phase17: require('../assets/images/Icons/sun-phases/phase17.png'),
  phase18: require('../assets/images/Icons/sun-phases/phase18.png'),
  phase19: require('../assets/images/Icons/sun-phases/phase19.png'),
  phase1: require('../assets/images/Icons/sun-phases/phase1.png'),
  phase20: require('../assets/images/Icons/sun-phases/phase20.png'),
  phase21: require('../assets/images/Icons/sun-phases/phase21.png'),
  phase22: require('../assets/images/Icons/sun-phases/phase22.png'),
  phase2: require('../assets/images/Icons/sun-phases/phase2.png'),
  phase3: require('../assets/images/Icons/sun-phases/phase3.png'),
  phase4: require('../assets/images/Icons/sun-phases/phase4.png'),
  phase5: require('../assets/images/Icons/sun-phases/phase5.png'),
  phase6: require('../assets/images/Icons/sun-phases/phase6.png'),
  phase7: require('../assets/images/Icons/sun-phases/phase7.png'),
  phase8: require('../assets/images/Icons/sun-phases/phase8.png'),
  phase9: require('../assets/images/Icons/sun-phases/phase9.png'),
  purpleArrowIcon: require('../assets/images/Icons/icon-purple-arrow.png'),
  slack: require('../assets/images/Icons/icon-slack.png'),
  thankYou: require('../assets/images/bg-thank-you.jpg'),
  theArmory: require('../assets/images/dreamhouse.png'),
  twitterIcon: require('../assets/images/Icons/icon-twitter-red.png'),
  uberButton: require('../assets/images/uber-button.png')
}


Images.forLocalCache = [
  Images.inactiveInstallations,
  Images.activeInstallations,
  Images.activeInfoIcon,
  Images.activeLocationIcon,
  Images.activeScheduleIcon,
  Images.inactiveInfoIcon,
  Images.inactiveLocationIcon,
  Images.inactiveScheduleIcon,
  Images.arrowIcon,
  Images.twitterIcon,
  Images.slack,
  Images.blowhorn,
  Images.theArmory,
];

export default Images;
